# Generated by Django 3.2.6 on 2021-08-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.IntegerField(),
        ),
    ]
