# Generated by Django 3.2.6 on 2021-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
