# Generated by Django 3.2.6 on 2021-10-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_precio_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='precio',
            new_name='ValorIntroducido',
        ),
    ]
