# Generated by Django 3.2.6 on 2021-10-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_rename_precio_valorintroducido'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorintroducido',
            name='resultado',
            field=models.IntegerField(default=0),
        ),
    ]
