# Generated by Django 3.2.6 on 2021-10-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_alter_resultados_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='resultado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='valorintroducido',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
