# Generated by Django 3.2.8 on 2021-10-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_auto_20211012_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('pais', models.CharField(choices=[('ves', 'Venezuela'), ('usd', 'United states'), ('gbp', 'United kingdom')], max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='resultados',
            name='resultado',
            field=models.FloatField(default=0),
        ),
    ]
