# Generated by Django 3.2.8 on 2021-11-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0016_auto_20211101_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoinprices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('priceves', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PriceukModel',
        ),
    ]
