# Generated by Django 3.2.8 on 2021-11-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0018_rename_price_bitcoinprices_priceuk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoinpriceuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceuk', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bitcoinpriceves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceves', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Bitcoinprices',
        ),
    ]
