# Generated by Django 3.2.8 on 2021-11-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0019_auto_20211101_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('temp_price', models.CharField(max_length=100)),
                ('max_amount_available', models.IntegerField(default=0)),
            ],
        ),
    ]
