# Generated by Django 3.2.8 on 2021-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0020_listas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listas',
            name='max_amount_available',
            field=models.FloatField(default=0),
        ),
    ]
